### ISSUE TITLE
Distributions are not properly handled

### ISSUE THREAD

**Issue by MetaGIS** [GeoCat/iso-19139-to-dcat-ap#4]
It seems whenwe have online links with where two online links share he same  protocol
With get same node-ID for several distrubutions and they get totally mixed up

Check dataset with this title
in ISO19139 in DCAT and how it looks like on dataportal.se

Nationella marktäckedata 2018; basskikt

**Comment by pvgenuchten** [comment]
i' suggest to use `gmd:url#metadata-identifier` as uri

**Comment by MichaelOstling** [comment]
Have you done any work on this?

**Comment by pvgenuchten** [comment]
@MichaelOstling this should be solved in https://github.com/GeoCat/iso-19139-to-dcat-ap/commit/434b83255416de3a6a634422da94b4f60c94ef3d, please confirm

**Comment by MetaGIS** [comment]
This seems no valid since it can break rules on http uris
https://tools.ietf.org/html/rfc3986#section-3.5
So maybe we shall just add a "/" 

It also seems we are transforming both DistributorTransferOptions and TransferOptions
We shall only transform DistributorTransferOptions

**Comment by MetaGIS** [comment]
We are still fetching both Transferoptions and DistributorTransferoption
The transformation shall only handle DistributorTransferOptions
We are still having duplicated distributions

**Comment by pvgenuchten** [comment]
This duplication in transferoptions and distributortransferoptions is related to the Swedish profile? If such a differentiation is made in the iso document, you don't want to apply it to the DCAT document?

Is distributortransferoptions used in all records, or should i fall back to transferoptions if distributortransferoptions is not populated?

**Comment by pvgenuchten** [comment]
fixed in https://github.com/GeoCat/iso-19139-to-dcat-ap/commit/e4ef254a6d5f3e67862674af0df3fd75bee7d085

**Comment by MetaGIS** [comment]
We shall always use only DistributorTransferOptions
I see transferoptions is commented xsl last week but I still get Distributions from both DistributorTransferOptions and TransferOptions

**Comment by MetaGIS** [comment]
[GSE_CSW_Oppnadata.zip](https://github.com/GeoCat/iso-19139-to-dcat-ap/files/6608730/GSE_CSW_Oppnadata.zip)

**Comment by pvgenuchten** [comment]
indeed, when multiple records reference the same wms service, the uri for that service will be duplicated, let me add a unique record reference
